name: Obfuscate JS and Commit

on:
  push:
    paths:
      - 'main.js'

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JavaScript Obfuscator
        run: npm install -g javascript-obfuscator

      - name: Obfuscate main.js
        run: javascript-obfuscator main.js --output main.js

      - name: Commit and push obfuscated file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global
